name = "MATIO"
uuid = "e0c5a735-509d-42f9-94ca-5bb507e3a62b"
authors = ["Marcin Koculak <koculak.marcin@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CodecZlib = "0.7.8"
Dates = "1.11.0"
SparseArrays = "1.10.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
